// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  ["How do I register my new business?", "business"],
  ["i want to start a startup in berlin", "business"],
  ["Wie melde ich ein Gewerbe an?", "business"],
  ["How do I do my Anmeldung?", "anmeldung"],
  ["I just moved, what do I have to do?", "anmeldung"],
  ["Wohnsitz ummelden", "anmeldung"],
  ["How do I get a new passport?", "passport"],
  ["my personalausweis expired", "passport"],
  ["How do I register my car?", "car"],
  ["Is there really no speed limit on the Autobahn?", "car"],
  ["How do I do my tax return?", "tax"],
  ["Wann muss ich meine Steuererklärung abgeben?", "tax"],
  ["Why is my train late again?", "train"],
  ["Deutsche Bahn Verspätung Entschädigung", "train"],
  ["Can I go shopping on Sunday?", "sunday"],
  ["is the supermarket open on sonntag", "sunday"],
  ["Which bin does a yoghurt pot go in?", "trash"],
  ["how does recycling work here", "trash"],
  ["Do I have to pay tax for my dog?", "dog"],
  ["How do I get a Kita place?", "kita"],
  ["How long is Elternzeit?", "kita"],
  ["Can I submit my documents by email?", "digital"],
  ["why is the internet so slow", "digital"],
  ["How do I get married in Germany?", "marriage"],
  ["Can I pay by card?", "cash"],
  ["why does nobody accept credit cards", "cash"],
  ["How do I rent an apartment?", "housing"],
  ["why do apartments have no kitchen", "housing"],
  ["How do I get an appointment at the Bürgeramt?", "termin"],
  ["Termin beim Buergeramt", "termin"],
  ["Do I have to pay the Rundfunkbeitrag?", "rundfunk"],
  ["I don't own a TV, do I still pay GEZ?", "rundfunk"],
  ["How do I see a doctor?", "health"],
  ["How do I get a sick note?", "sicknote"],
  ["How do I cancel my gym contract?", "kuendigung"],
  ["Vertrag kündigen per Einschreiben", "kuendigung"],
  ["How do I open a bank account?", "bank"],
  ["What is a SCHUFA?", "bank"],
  ["How do I become a German citizen?", "citizenship"],
  ["How many vacation days do I get?", "work"],
  ["What is a Brückentag?", "brueckentag"],
  ["Is beer food?", "beer"],
  ["when is oktoberfest", "beer"],
  ["What are the Ruhezeiten?", "noise"],
  ["my neighbour is too loud", "noise"],
  ["Who is Frau Schulze?", "schulze"],
  ["What is the weather like?", "weather"],
  ["Why do Germans open all the windows?", "lueften"],
  ["Is tap water free in restaurants?", "restaurant"],
  ["how much should I tip the waiter", "restaurant"],
  ["Can I ride my bike on the pavement?", "bike"],
  ["Can I cross on red?", "redlight"],
  ["Where can I park?", "parking"],
  ["Tell me a joke", "joke"],
  ["Who are you?", "identity"],
  ["are you chatgpt", "identity"],
  ["Can I speak to a human?", "human"],
  ["I want to file a Widerspruch", "widerspruch"],
  ["What are your opening hours?", "hours"],
  ["Where can I buy bread on Sunday morning?", "food"],
  ["Can I call my baby Pumuckl?", "babyname"],
  ["Where do I get a certified copy?", "beglaubigung"],
  ["Is the Deutschlandticket worth it?", "deutschlandticket"],
  ["When can I retire?", "pension"],
  ["My DHL parcel was not delivered", "post"],
  ["Is the fax secure?", "fax"],
];
