// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  ["Is it rude to be early?", "culture-punctuality"],
  ["How punctual do I have to be for a meeting?", "culture-punctuality"],
  ["what happens if i'm 5 minutes late", "culture-punctuality"],
  ["Ist es schlimm, wenn ich zu spät komme?", "culture-punctuality"],
  ["Why do Germans love football so much?", "culture-football"],
  ["Who will win the Bundesliga?", "culture-football"],
  ["Can I go to the Stammtisch?", "culture-football"],
  ["where can i watch the world cup", "culture-football"],
  ["What is Karneval?", "culture-karneval"],
  ["Do I have to wear a costume for Fasching?", "culture-karneval"],
  ["helau or alaaf?", "culture-karneval"],
  ["Why did someone cut my tie on Weiberfastnacht?", "culture-karneval"],
  ["What is a Weihnachtsmarkt?", "culture-weihnachtsmarkt"],
  ["why is there pfand on my glühwein mug", "culture-weihnachtsmarkt"],
  ["When does the Christmas market open?", "culture-weihnachtsmarkt"],
  ["Was macht der Nikolaus?", "culture-weihnachtsmarkt"],
  ["Why is dancing banned on Good Friday?", "culture-easter"],
  ["What do Germans do at Easter?", "culture-easter"],
  ["where does the osterhase hide eggs", "culture-easter"],
  ["How do I behave in a sauna?", "culture-sauna"],
  ["Do I have to be naked in the sauna?", "culture-sauna"],
  ["What is an Aufguss?", "culture-sauna"],
  ["what is fkk", "culture-sauna"],
  ["Can I reserve a sun lounger with a towel?", "culture-pool-towel"],
  ["Why are there towels on all the loungers by the pool?", "culture-pool-towel"],
  ["handtuch auf der liege reservieren", "culture-pool-towel"],
  ["What is a Schrebergarten?", "culture-schrebergarten"],
  ["How do I get an allotment garden?", "culture-schrebergarten"],
  ["are garden gnomes allowed", "culture-schrebergarten"],
  ["What are the rules in a Kleingartenverein?", "culture-schrebergarten"],
  ["What is a Verein?", "culture-verein"],
  ["How do I start a Verein?", "culture-verein"],
  ["Is there a club for my hobby?", "culture-verein"],
  ["Why do Germans take off their shoes?", "culture-guest"],
  ["What should I bring when I'm invited?", "culture-guest"],
  ["Is it ok to bring flowers to a dinner party?", "culture-guest"],
  ["do i need to wear the guest slippers", "culture-guest"],
  ["Why do Germans wear socks in sandals?", "culture-socks-sandals"],
  ["Are Birkenstocks acceptable at work?", "culture-socks-sandals"],
  ["What is the German dress code?", "culture-socks-sandals"],
  ["Should I say du or Sie?", "culture-duzen"],
  ["How do I address my boss?", "culture-duzen"],
  ["when can i start duzen my colleagues", "culture-duzen"],
  ["Do I have to say Herr Doktor?", "culture-duzen"],
  ["Why are Germans so direct?", "culture-directness"],
  ["Why don't Germans do small talk?", "culture-directness"],
  ["why do germans never smile", "culture-directness"],
  ["Are Germans rude?", "culture-directness"],
  ["How do I learn German?", "culture-language"],
  ["Why is der die das so hard?", "culture-language"],
  ["What is the longest word in German?", "culture-language"],
  ["Wo finde ich einen Deutschkurs?", "culture-language"],
  ["Why are there so many dialects?", "culture-dialect"],
  ["I don't understand Bavarian", "culture-dialect"],
  ["is sächsisch a real language", "culture-dialect"],
  ["Why does everyone watch Tatort on Sunday?", "culture-tatort"],
  ["Can I call someone during Tatort?", "culture-tatort"],
  ["what's on german tv tonight", "culture-tatort"],
  ["Why do Germans love Mallorca?", "culture-mallorca-schlager"],
  ["Why do Germans love Schlager?", "culture-mallorca-schlager"],
  ["What is Ballermann?", "culture-mallorca-schlager"],
  ["Why do Germans love David Hasselhoff?", "culture-mallorca-schlager"],
  ["Why do Germans wear Jack Wolfskin?", "culture-wandern"],
  ["Where can I go hiking?", "culture-wandern"],
  ["sonntags spaziergang pflicht?", "culture-wandern"],
  ["What happens on Silvester?", "culture-silvester"],
  ["Why do Germans watch Dinner for One?", "culture-silvester"],
  ["When can I buy fireworks?", "culture-silvester"],
  ["Why do Germans queue so strictly?", "culture-queue"],
  ["someone cut in line at the supermarket", "culture-queue"],
  ["Warum drängeln alle an der Kasse vor?", "culture-queue"],
  ["Is beer food?", "beer"],
  ["When is Oktoberfest?", "beer"],
];
