// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  ["Can I homeschool my kids in Germany?", "family-homeschool"],
  ["is homeschooling legal", "family-homeschool"],
  ["Can we take the kids out of school a few days early for vacation?", "family-homeschool"],
  ["Was passiert wenn mein Kind die Schule schwänzt?", "family-homeschool"],
  ["How does the German school system work?", "family-schoolsystem"],
  ["Gymnasium or Realschule for my daughter?", "family-schoolsystem"],
  ["what is a Grundschule", "family-schoolsystem"],
  ["Why is a 1 the best grade? how does the schulsystem work", "family-schoolsystem"],
  ["What is the Abitur?", "family-abitur"],
  ["what grade do i need in my abi for medicine (numerus clausus)", "family-abitur"],
  ["Is the Abitur the same as A-levels?", "family-abitur"],
  ["How do I apply to university?", "family-university"],
  ["Do I have to pay tuition fees at a German university?", "family-university"],
  ["what is the semesterbeitrag", "family-university"],
  ["Wie läuft die Immatrikulation an der Uni?", "family-university"],
  ["What is BAföG?", "family-bafoeg"],
  ["how do i apply for bafoeg", "family-bafoeg"],
  ["Can I get a student loan from the state?", "family-bafoeg"],
  ["I'm pregnant, what do I need to do?", "family-hebamme"],
  ["How do I find a midwife?", "family-hebamme"],
  ["Ich bin schwanger und finde keine Hebamme", "family-hebamme"],
  ["What should I bring when I give birth in the hospital?", "family-hebamme"],
  ["What is Mutterschutz?", "family-mutterschutz"],
  ["how long is maternity leave in germany", "family-mutterschutz"],
  ["When do I have to tell my employer that I'm pregnant?", "family-mutterschutz"],
  ["How do I apply for Elterngeld?", "family-elterngeld"],
  ["What is the difference between Elterngeld and ElterngeldPlus?", "family-elterngeld"],
  ["how much parental allowance do i get", "family-elterngeld"],
  ["How do I find a Kinderarzt?", "family-kinderarzt"],
  ["What are the U-Untersuchungen?", "family-kinderarzt"],
  ["I lost the gelbes Heft of my son", "family-kinderarzt"],
  ["Is there a pediatrician taking new patients?", "family-kinderarzt"],
  ["What vaccinations does my child need?", "family-impfung"],
  ["Do kids need a measles vaccination for Kita?", "family-impfung"],
  ["i lost my impfpass", "family-impfung"],
  ["Where is the nearest pharmacy open at night?", "family-apotheke"],
  ["Why can't I buy ibuprofen in the supermarket?", "family-apotheke"],
  ["How does the E-Rezept work?", "family-apotheke"],
  ["Apotheke Notdienst am Sonntag?", "family-apotheke"],
  ["Should I get private or public insurance?", "family-privat"],
  ["What's the difference between gesetzlich versichert and privat versichert?", "family-privat"],
  ["Is private health insurance worth it?", "family-privat"],
  ["How do I find a dentist?", "family-zahnarzt"],
  ["Does insurance pay for braces for my kid?", "family-zahnarzt"],
  ["what is a bonusheft at the zahnarzt", "family-zahnarzt"],
  ["How long is the waiting list for a therapist?", "family-therapie"],
  ["I need mental health support", "family-therapie"],
  ["Wie finde ich einen Psychotherapeuten?", "family-therapie"],
  ["How do I get a Pflegegrad for my mother?", "family-pflege"],
  ["how do i find a nursing home for my dad", "family-pflege"],
  ["My elderly parent needs care, what do I do?", "family-pflege"],
  ["How do I plan a children's birthday party?", "family-geburtstag"],
  ["What games do you play at a Kindergeburtstag?", "family-geburtstag"],
  ["How many kids should I invite to the party for my kid?", "family-geburtstag"],
  ["What is the Einschulung?", "family-einschulung"],
  ["What goes in a Schultüte?", "family-einschulung"],
  ["what do we need for the first day of school", "family-einschulung"],
  ["What is Sankt Martin?", "family-laterne"],
  ["Why do kids walk around with lanterns in November?", "family-laterne"],
  ["Where can my kid get the Seepferdchen?", "family-seepferdchen"],
  ["how do i find swimming lessons for my son", "family-seepferdchen"],
  ["How does an Ausbildung work?", "family-ausbildung"],
  ["Can I do an apprenticeship in Germany?", "family-ausbildung"],
  ["Wie hoch ist die Ausbildungsvergütung für Azubis?", "family-ausbildung"],
  ["Can grandma look after my baby instead of Kita?", "family-oma"],
  ["How do I find a Tagesmutter?", "family-oma"],
  ["can i hire an au pair", "family-oma"],
  ["How do I get a Kita place?", "kita"],
  ["How do I apply for Kindergeld?", "kita"],
];
