// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  ["How do I extend my residence permit?", "gov-residence-permit"],
  ["my aufenthaltstitel expires next month what do i do", "gov-residence-permit"],
  ["Why can't I get an appointment at the Ausländerbehörde?", "gov-residence-permit"],
  ["What is a Fiktionsbescheinigung?", "gov-residence-permit"],
  ["Wie bekomme ich eine Niederlassungserlaubnis?", "gov-residence-permit"],
  ["How do I get a Blue Card?", "gov-blue-card"],
  ["Do I need a work permit to work in Germany?", "gov-blue-card"],
  ["how long does a work visa take", "gov-blue-card"],
  ["What is the Chancenkarte?", "gov-blue-card"],
  ["How do I get my foreign degree recognised?", "gov-anerkennung"],
  ["Is my qualification valid in Germany?", "gov-anerkennung"],
  ["Anerkennung von ausländischen Abschlüssen", "gov-anerkennung"],
  ["How do I use the AusweisApp?", "gov-eid"],
  ["I lost my PIN letter for my ID card", "gov-eid"],
  ["what is the online ausweis", "gov-eid"],
  ["Does the eID actually work?", "gov-eid"],
  ["How do I vote in Germany?", "gov-voting"],
  ["How does Briefwahl work?", "gov-voting"],
  ["I didn't get my Wahlbenachrichtigung", "gov-voting"],
  ["where is my polling station", "gov-voting"],
  ["Can I vote online?", "gov-voting"],
  ["How does the German government work?", "gov-federalism"],
  ["What is the difference between Bundestag and Bundesrat?", "gov-federalism"],
  ["Why does every Bundesland have different rules?", "gov-federalism"],
  ["who is in charge of germany", "gov-federalism"],
  ["What is Föderalismus?", "gov-federalism"],
  ["What does the DSGVO mean for me?", "gov-dsgvo"],
  ["Can I delete my data?", "gov-dsgvo"],
  ["is gdpr the reason my doctor won't email me", "gov-dsgvo"],
  ["How do I make a data protection request?", "gov-dsgvo"],
  ["My wallet was stolen, what do I do?", "gov-police"],
  ["How do I report a crime?", "gov-police"],
  ["what is the emergency number in germany", "gov-police"],
  ["Wie erstatte ich eine Anzeige bei der Polizei?", "gov-police"],
  ["Someone broke into my apartment, burglary", "gov-police"],
  ["I lost my wallet, what do I do?", "gov-lost-property"],
  ["Where is the Fundbüro?", "gov-lost-property"],
  ["I found a phone on the street", "gov-lost-property"],
  ["Do I get a reward for returning lost property?", "gov-lost-property"],
  ["How do I get a Führungszeugnis?", "gov-fuehrungszeugnis"],
  ["I need a criminal record check for my new job", "gov-fuehrungszeugnis"],
  ["certificate of good conduct germany", "gov-fuehrungszeugnis"],
  ["What is the fine for not picking up dog poop?", "gov-ordnungsamt"],
  ["I got a fine from the Ordnungsamt", "gov-ordnungsamt"],
  ["How much is the Bußgeld for throwing a cigarette butt?", "gov-ordnungsamt"],
  ["How do I register a demonstration?", "gov-demonstration"],
  ["Can I protest in Germany?", "gov-demonstration"],
  ["wie melde ich eine Kundgebung an", "gov-demonstration"],
  ["Do I need a building permit for a shed?", "gov-building"],
  ["Can I build a carport in my garden?", "gov-building"],
  ["My house is a listed building, can I change the windows?", "gov-building"],
  ["Brauche ich eine Baugenehmigung für ein Gartenhaus?", "gov-building"],
  ["Do I need to register my solar panel?", "gov-energy"],
  ["How do I register a Balkonkraftwerk?", "gov-energy"],
  ["Should I get a heat pump?", "gov-energy"],
  ["What is the Heizungsgesetz?", "gov-energy"],
  ["Where do I find my Steuer-ID?", "gov-steuer-id"],
  ["I lost my tax ID", "gov-steuer-id"],
  ["what's the difference between steuernummer and steuer-id", "gov-steuer-id"],
  ["Which office is responsible for me?", "gov-zustaendigkeit"],
  ["Every office sent me to another office", "gov-zustaendigkeit"],
  ["They said they are nicht zuständig", "gov-zustaendigkeit"],
  ["Is German administration digital?", "gov-e-akte"],
  ["Why is everything on paper in Germany?", "gov-e-akte"],
  ["What is the OZG?", "gov-e-akte"],
  ["Is AI regulated in Germany? What about the AI Act?", "gov-ai-act"],
  ["Is artificial intelligence legal in Germany?", "gov-ai-act"],
  ["How do I become a Beamter?", "gov-beamter"],
  ["Can civil servants be fired?", "gov-beamter"],
  ["I want to work for the government", "gov-beamter"],
  ["Should I get legal insurance?", "gov-court"],
  ["I got an Abmahnung for a photo on my website", "gov-court"],
  ["Does my blog need an Impressum?", "gov-court"],
  ["I was selected as a Schöffe, can I say no?", "gov-court"],
  ["How do I find a lawyer?", "gov-court"],
  ["How do I extend my visa?", "passport"],
  ["How do I become a German citizen?", "citizenship"],
];
