// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  ["What is the Kehrwoche?", "housing-kehrwoche"],
  ["Do I really have to clean the stairs every week?", "housing-kehrwoche"],
  ["Wer muss das Treppenhaus putzen?", "housing-kehrwoche"],
  ["our building has a cleaning schedule, what happens if i skip it", "housing-kehrwoche"],
  ["What is in my Nebenkostenabrechnung?", "housing-nebenkosten"],
  ["Why is my utility bill so high?", "housing-nebenkosten"],
  ["I got a Nachzahlung of 600 euros, is that normal?", "housing-nebenkosten"],
  ["Was sind Betriebskosten?", "housing-nebenkosten"],
  ["What is in the Hausordnung?", "housing-hausordnung"],
  ["What are the house rules in a German building?", "housing-hausordnung"],
  ["can the Hausordnung forbid bikes in the hallway", "housing-hausordnung"],
  ["How do I organize my Umzug?", "housing-umzug"],
  ["Where do I get moving boxes?", "housing-umzug"],
  ["How do I set up mail forwarding?", "housing-umzug"],
  ["Do I get a day off for moving day?", "housing-umzug"],
  ["Wie beantrage ich einen Nachsendeauftrag?", "housing-umzug"],
  ["Can I use the washing machine at night?", "housing-keller"],
  ["How do I book the laundry room?", "housing-keller"],
  ["What can I store in my Keller?", "housing-keller"],
  ["why is the basement light always off", "housing-keller"],
  ["Can I grill on my balcony?", "housing-grill"],
  ["Is a BBQ allowed in my apartment building?", "housing-grill"],
  ["Darf ich auf dem Balkon grillen?", "housing-grill"],
  ["Do I have to let the Schornsteinfeger in?", "housing-schornsteinfeger"],
  ["Why is a chimney sweep coming to my flat?", "housing-schornsteinfeger"],
  ["How do I switch electricity provider?", "housing-strom"],
  ["How do I read my electricity meter?", "housing-strom"],
  ["Why is my power bill so expensive?", "housing-strom"],
  ["Wie wechsle ich meinen Stromanbieter?", "housing-strom"],
  ["How do I reduce my heating costs?", "housing-heizkosten"],
  ["What do the numbers on the thermostat mean?", "housing-heizkosten"],
  ["My radiator is cold, what can I do?", "housing-heizkosten"],
  ["Can my landlord raise the rent?", "housing-mietpreisbremse"],
  ["What is the Mietpreisbremse?", "housing-mietpreisbremse"],
  ["my rent went up by 15 percent, is that legal", "housing-mietpreisbremse"],
  ["What is an Indexmiete?", "housing-mietpreisbremse"],
  ["Will I get my deposit back?", "housing-kaution"],
  ["How much Kaution can a landlord ask for?", "housing-kaution"],
  ["What happens at the move-out inspection?", "housing-kaution"],
  ["Do I have to renovate when I move out?", "housing-renovieren"],
  ["Do I have to paint the walls white again?", "housing-renovieren"],
  ["Muss ich beim Auszug streichen?", "housing-renovieren"],
  ["How do I find a room in a WG?", "housing-wg"],
  ["What is a WG-Casting?", "housing-wg"],
  ["my flatmate never cleans, what do i do", "housing-wg"],
  ["How do I report a repair to the Hausverwaltung?", "housing-reparatur"],
  ["My tap is leaking and nobody answers", "housing-reparatur"],
  ["Can I reduce my rent if the heater is broken? Mietminderung?", "housing-reparatur"],
  ["When does the Hausmeister come?", "housing-reparatur"],
  ["Why do I need my name on the doorbell?", "housing-klingelschild"],
  ["How do I get a name tag for my Briefkasten?", "housing-klingelschild"],
  ["How do I get rid of an old sofa?", "housing-sperrmuell"],
  ["What is Sperrmüll?", "housing-sperrmuell"],
  ["Where do I throw away an old mattress?", "housing-sperrmuell"],
  ["When is the trash collected?", "housing-abholtag"],
  ["When do I have to put the bins out?", "housing-abholtag"],
  ["Wann ist die Müllabfuhr?", "housing-abholtag"],
  ["Can I drill holes in the wall?", "housing-duebel"],
  ["How do I hang a picture in a rented flat?", "housing-duebel"],
  ["Which Dübel do I need?", "housing-duebel"],
  ["How tall can my neighbour's hedge be?", "housing-hecke"],
  ["The neighbor's tree has branches over my garden", "housing-hecke"],
  ["Wie hoch darf ein Gartenzaun sein?", "housing-hecke"],
  ["I locked myself out, what do I do?", "housing-schluesseldienst"],
  ["How much does a Schlüsseldienst cost?", "housing-schluesseldienst"],
  ["I lost my keys, can I get a spare key?", "housing-schluesseldienst"],
  ["How do I rent an apartment?", "housing"],
  ["Why do apartments have no kitchen?", "housing"],
  ["Why do Germans open all the windows?", "lueften"],
];
