// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  ["Do I need liability insurance?", "life-haftpflicht"],
  ["What is a Haftpflichtversicherung?", "life-haftpflicht"],
  ["i broke my friend's tv, who pays?", "life-haftpflicht"],
  ["Brauche ich eine Privathaftpflicht?", "life-haftpflicht"],
  ["I damaged my neighbour's car with my bike", "life-haftpflicht"],
  ["personal liability insurance germany", "life-haftpflicht"],
  ["Do I need household contents insurance?", "life-hausrat"],
  ["What does Hausratversicherung cover?", "life-hausrat"],
  ["is home insurance worth it", "life-hausrat"],
  ["Lohnt sich eine Hausratversicherung?", "life-hausrat"],
  ["How many insurances do Germans have?", "life-versicherungen"],
  ["Which insurance do I need in Germany?", "life-versicherungen"],
  ["an insurance agent wants to meet me", "life-versicherungen"],
  ["Is a Versicherungsmakler worth it?", "life-versicherungen"],
  ["Do I need Zahnzusatzversicherung?", "life-versicherungen"],
  ["should I get disability insurance", "life-versicherungen"],
  ["Welche Versicherungen brauche ich?", "life-versicherungen"],
  ["How do I write a will?", "life-erbe"],
  ["How does inheritance work in Germany?", "life-erbe"],
  ["Was ist ein Erbschein?", "life-erbe"],
  ["i will inherit my grandma's house", "life-erbe"],
  ["Is a handwritten Testament valid?", "life-erbe"],
  ["Do I pay Erbschaftssteuer?", "life-erbe"],
  ["How do I make a will in germany", "life-erbe"],
  ["My father died, what do I have to do?", "life-funeral"],
  ["How does a funeral work in Germany?", "life-funeral"],
  ["Can I keep my mother's ashes at home?", "life-funeral"],
  ["Wie bekomme ich eine Sterbeurkunde?", "life-funeral"],
  ["how long can you rent a grave", "life-funeral"],
  ["Was kostet eine Beerdigung?", "life-funeral"],
  ["someone died in my family, paperwork?", "life-funeral"],
  ["Is there a Friedhofszwang?", "life-funeral"],
  ["How do I leave the church?", "life-kirchenaustritt"],
  ["Kirchenaustritt wie?", "life-kirchenaustritt"],
  ["How do I leave the church to stop paying church tax?", "life-kirchenaustritt"],
  ["Wie trete ich aus der Kirche aus?", "life-kirchenaustritt"],
  ["does leaving the church cost money", "life-kirchenaustritt"],
  ["Can I change my name?", "life-namechange"],
  ["how do I change my surname after marriage", "life-namechange"],
  ["Can we have a Doppelname?", "life-namechange"],
  ["Namensänderung beantragen", "life-namechange"],
  ["can i take her name when we marry", "life-namechange"],
  ["What is a Vorsorgevollmacht?", "life-vollmacht"],
  ["How do I write a Patientenverfügung?", "life-vollmacht"],
  ["do I need a power of attorney for my parents", "life-vollmacht"],
  ["What is a living will?", "life-vollmacht"],
  ["Brauche ich eine Betreuungsverfügung?", "life-vollmacht"],
  ["How long do I have to keep documents?", "life-ordner"],
  ["How long should I keep my payslips?", "life-ordner"],
  ["Can I shred old bank statements?", "life-ordner"],
  ["Wie lange muss ich Unterlagen aufbewahren?", "life-ordner"],
  ["how do Germans organize their paperwork", "life-ordner"],
  ["why does everyone have a leitz ordner", "life-ordner"],
  ["How do I become an organ donor?", "life-organspende"],
  ["Where do I get an Organspendeausweis?", "life-organspende"],
  ["Is Germany opt-in for organ donation?", "life-organspende"],
  ["where can I donate blood", "life-organspende"],
  ["How do I get a copy of my birth certificate?", "life-geburtsurkunde"],
  ["Geburtsurkunde beantragen", "life-geburtsurkunde"],
  ["I lost my birth certificate", "life-geburtsurkunde"],
  ["Where do I get an international birth certificate?", "life-geburtsurkunde"],
  ["How do I register a birth?", "life-birth-registration"],
  ["We just had a baby, what do we need to do?", "life-birth-registration"],
  ["how to register my newborn", "life-birth-registration"],
  ["Geburt anmelden Standesamt", "life-birth-registration"],
  ["Our baby was born yesterday, what now?", "life-birth-registration"],
  ["We are not married but have a child", "life-unmarried"],
  ["How does custody work if we're unmarried?", "life-unmarried"],
  ["What is a Vaterschaftsanerkennung?", "life-unmarried"],
  ["Rechte als unverheiratetes Paar", "life-unmarried"],
  ["we want to live together without being married", "life-unmarried"],
  ["How do I get a Schufa entry removed?", "life-schufa-entry"],
  ["I have a negative Schufa", "life-schufa-entry"],
  ["how can I improve my schufa score", "life-schufa-entry"],
  ["Schufa-Eintrag löschen lassen", "life-schufa-entry"],
  ["How do I get a free Schufa Auskunft?", "life-schufa-entry"],
  ["I'm in debt, where can I get help?", "life-debt"],
  ["Ich habe Schulden, was tun?", "life-debt"],
  ["i can't pay my bills", "life-debt"],
  ["How does Privatinsolvenz work?", "life-debt"],
  ["Where is a free Schuldnerberatung?", "life-debt"],
  ["I got a letter from an Inkasso company", "life-inkasso"],
  ["What do I do with a Mahnbescheid?", "life-inkasso"],
  ["debt collector keeps writing to me", "life-inkasso"],
  ["Ich habe eine Mahnung bekommen", "life-inkasso"],
  ["is this inkasso letter fake", "life-inkasso"],
  ["What changes when I turn 18?", "life-18"],
  ["Was darf ich mit 18?", "life-18"],
  ["my son is turning 18 soon", "life-18"],
  ["Ab wann ist man volljährig?", "life-18"],
  ["How do I play Lotto?", "life-lotto"],
  ["Are lottery winnings taxed in Germany?", "life-lotto"],
  ["Lotto 6 aus 49 Chancen", "life-lotto"],
  ["what if I win the jackpot", "life-lotto"],
];
