// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  ["How do I convert my foreign driving licence?", "mobility-licence-conversion"],
  ["Can I exchange my US driver's license for a German one?", "mobility-licence-conversion"],
  ["is my american driving licence valid in germany", "mobility-licence-conversion"],
  ["Führerschein umschreiben lassen, wie geht das?", "mobility-licence-conversion"],
  ["Do I need an international driving permit?", "mobility-licence-conversion"],
  ["How much does a driving licence cost?", "mobility-fahrschule"],
  ["how expensive is fahrschule", "mobility-fahrschule"],
  ["What is the theory test like?", "mobility-fahrschule"],
  ["I failed my driving test, what now?", "mobility-fahrschule"],
  ["Where can I learn to drive?", "mobility-fahrschule"],
  ["When does my car need TÜV?", "mobility-tuev"],
  ["What is the Hauptuntersuchung?", "mobility-tuev"],
  ["my car failed the tüv", "mobility-tuev"],
  ["How often is a vehicle inspection required?", "mobility-tuev"],
  ["Why is there always a Stau?", "mobility-stau"],
  ["why so many construction sites on the autobahn", "mobility-stau"],
  ["What is a Rettungsgasse?", "mobility-stau"],
  ["How bad is the holiday traffic in summer?", "mobility-stau"],
  ["Stuck in a traffic jam on the A7, help", "mobility-stau"],
  ["I got flashed by a speed camera", "mobility-speeding"],
  ["What happens if I get caught speeding?", "mobility-speeding"],
  ["How many points in Flensburg do I have?", "mobility-speeding"],
  ["Ich wurde geblitzt, was kostet das?", "mobility-speeding"],
  ["Do I need a green sticker for Berlin?", "mobility-umweltzone"],
  ["What is an Umweltzone?", "mobility-umweltzone"],
  ["Is there a diesel ban in Stuttgart?", "mobility-umweltzone"],
  ["Do I need a toll vignette for the Autobahn?", "mobility-maut"],
  ["Is there a Maut for cars in Germany?", "mobility-maut"],
  ["Is BER finally open?", "mobility-ber"],
  ["Why did the Berlin airport take so long to build?", "mobility-ber"],
  ["what happened to tegel", "mobility-ber"],
  ["What are my rights if my flight is cancelled?", "mobility-flights"],
  ["Lufthansa lost my luggage", "mobility-flights"],
  ["My flight is delayed 4 hours, do I get money?", "mobility-flights"],
  ["Is there a train strike tomorrow?", "mobility-strike"],
  ["Is the GDL on strike again?", "mobility-strike"],
  ["Why are the train drivers always striking? Bahnstreik again?", "mobility-strike"],
  ["Is there a strike at the airport today?", "mobility-strike"],
  ["Is Flixbus a good alternative to the train?", "mobility-fernbus"],
  ["Where does the long distance bus leave from?", "mobility-fernbus"],
  ["How do I get a taxi?", "mobility-taxi"],
  ["Can I take an Uber in Berlin?", "mobility-taxi"],
  ["Why are all taxis beige?", "mobility-taxi"],
  ["Can I ride an e-scooter on the pavement?", "mobility-escooter"],
  ["are e scooters allowed after drinking", "mobility-escooter"],
  ["My bike was stolen, what do I do?", "mobility-bike-theft"],
  ["Mein Fahrrad wurde geklaut", "mobility-bike-theft"],
  ["What is the best bike lock?", "mobility-bike-theft"],
  ["Is a BahnCard worth it?", "mobility-bahncard"],
  ["Why are train tickets so expensive?", "mobility-bahncard"],
  ["What is the difference between Sparpreis and Flexpreis?", "mobility-bahncard"],
  ["Someone is sitting in my reserved seat", "mobility-quiet-zone"],
  ["Can I make phone calls in the quiet zone?", "mobility-quiet-zone"],
  ["Can I reserve a seat on the train?", "mobility-quiet-zone"],
  ["Why is there a replacement bus instead of my train?", "mobility-sev"],
  ["What is Schienenersatzverkehr?", "mobility-sev"],
  ["Why are fuel prices so high?", "mobility-fuel"],
  ["When is petrol cheapest?", "mobility-fuel"],
  ["Is E10 bad for my car?", "mobility-fuel"],
  ["Do I need winter tyres?", "mobility-winter-tyres"],
  ["when do i have to put on winter tires", "mobility-winter-tyres"],
  ["What does O bis O mean?", "mobility-winter-tyres"],
  ["What do I do after a car accident?", "mobility-accident"],
  ["Someone scratched my car in the parking lot", "mobility-accident"],
  ["Do I need a warning triangle in my car?", "mobility-accident"],
  ["Hatte einen Unfall, was muss ich tun?", "mobility-accident"],
  ["Is there really no speed limit on the Autobahn?", "car"],
  ["How do I get compensation for my delayed train?", "train"],
];
