// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  ["What is Berlin like?", "place-berlin"],
  ["Is Berlin worth visiting?", "place-berlin"],
  ["How do I get into Berghain?", "place-berlin"],
  ["Is Kreuzberg a good area?", "place-berlin"],
  ["why is berlin always under construction", "place-berlin"],
  ["Berlin arm aber sexy?", "place-berlin"],
  ["Is Neukölln safe?", "place-berlin"],
  ["What is Munich like?", "place-munich"],
  ["Can you surf in Munich?", "place-munich"],
  ["Is München expensive?", "place-munich"],
  ["what is the eisbach", "place-munich"],
  ["Englischer Garten or Central Park?", "place-munich"],
  ["What is Hamburg like?", "place-hamburg"],
  ["When is the Hamburg Fischmarkt?", "place-hamburg"],
  ["does it always rain in hamburg", "place-hamburg"],
  ["How much did the Elbphilharmonie cost?", "place-hamburg"],
  ["What is the Reeperbahn?", "place-hamburg"],
  ["What is Cologne like?", "place-cologne"],
  ["Why are Kölsch glasses so small?", "place-cologne"],
  ["Can I order Altbier in Köln?", "place-cologne"],
  ["When will the Kölner Dom be finished?", "place-cologne"],
  ["Cologne vs Düsseldorf?", "place-cologne"],
  ["What is Äppelwoi?", "place-frankfurt"],
  ["Is Frankfurt worth visiting?", "place-frankfurt"],
  ["why is it called mainhattan", "place-frankfurt"],
  ["What is Grüne Soße?", "place-frankfurt"],
  ["When will Stuttgart 21 be finished?", "place-stuttgart"],
  ["What is Stuttgart like?", "place-stuttgart"],
  ["how do you make spätzle", "place-stuttgart"],
  ["What are Maultaschen?", "place-stuttgart"],
  ["What is the Ruhrgebiet?", "place-ruhr"],
  ["where can I get the best currywurst", "place-ruhr"],
  ["What does Currywurst Pommes Schranke mean?", "place-ruhr"],
  ["Is Duisburg nice?", "place-ruhr"],
  ["What is a Trinkhalle?", "place-ruhr"],
  ["Is Leipzig the new Berlin?", "place-saxony"],
  ["What should I see in Dresden?", "place-saxony"],
  ["Is the Frauenkirche open?", "place-saxony"],
  ["What is the Erzgebirge famous for?", "place-saxony"],
  ["Is Weimar worth a trip?", "place-saxony"],
  ["Does Bielefeld exist?", "place-bielefeld"],
  ["What is the Bielefeld conspiracy?", "place-bielefeld"],
  ["bielefeld", "place-bielefeld"],
  ["What is a Strandkorb?", "place-coast"],
  ["Why do I have to pay Kurtaxe?", "place-coast"],
  ["Nordsee oder Ostsee?", "place-coast"],
  ["Can I go Wattwandern alone?", "place-coast"],
  ["Is Sylt worth visiting?", "place-coast"],
  ["best beach in germany", "place-coast"],
  ["How high is the Zugspitze?", "place-alps"],
  ["Where can I go skiing in Germany?", "place-alps"],
  ["Is there a ski resort near Munich?", "place-alps"],
  ["Is the Königssee worth it?", "place-alps"],
  ["Die Alpen im Sommer?", "place-alps"],
  ["Is Neuschwanstein worth it?", "place-castles"],
  ["How do I book tickets for Neuschwanstein?", "place-castles"],
  ["What is the Loreley?", "place-castles"],
  ["best castles on the Rhine", "place-castles"],
  ["Is Heidelberg castle a ruin?", "place-castles"],
  ["What should I see as a tourist?", "place-tourist"],
  ["First time in Germany, what should I do?", "place-tourist"],
  ["What are the must-see sights?", "place-tourist"],
  ["I'm planning a trip to Germany", "place-tourist"],
  ["Sehenswürdigkeiten in Deutschland", "place-tourist"],
  ["What time is hotel check-out?", "place-hotel"],
  ["Why do I have to fill in a form at the hotel?", "place-hotel"],
  ["Is a Jugendherberge nice?", "place-hotel"],
  ["Should I book an Airbnb or a hotel?", "place-hotel"],
  ["When does the breakfast buffet close?", "place-hotel"],
  ["Is wild camping allowed in Germany?", "place-camping"],
  ["Can I sleep in my campervan anywhere?", "place-camping"],
  ["Wo darf ich mit dem Wohnmobil stehen?", "place-camping"],
  ["Can I put up a tent in the forest?", "place-camping"],
  ["What are the rules at a Campingplatz?", "place-camping"],
  ["What is a good souvenir from Germany?", "place-souvenir"],
  ["Where can I buy a cuckoo clock?", "place-souvenir"],
  ["Is a garden gnome a good souvenir?", "place-souvenir"],
  ["Is a Nussknacker a good gift?", "place-souvenir"],
  ["Which is the best Bundesland?", "place-bundesland"],
  ["Where should I live in Germany?", "place-bundesland"],
  ["What is the most beautiful city in Germany?", "place-bundesland"],
  ["best place to live", "place-bundesland"],
  ["Is it boring to live in a village?", "place-smalltown"],
  ["What is the biggest city in Germany?", "place-smalltown"],
  ["Leben auf dem Dorf", "place-smalltown"],
  ["Is life in the countryside nice?", "place-smalltown"],
  ["Are museums open on Monday?", "place-landmarks"],
  ["How do I visit the Reichstag dome?", "place-landmarks"],
  ["Is the Brandenburger Tor free?", "place-landmarks"],
  ["How tall is the Fernsehturm?", "place-landmarks"],
  ["Why are museums closed on Mondays?", "place-landmarks"],
  // City + another topic: the other topic must win.
  ["How do I do my Anmeldung in Berlin?", "anmeldung"],
  ["How do I rent an apartment in Munich?", "housing"],
  ["Is there a train strike in Hamburg?", "mobility-strike"],
  ["When is Karneval in Köln?", "culture-karneval"],
  ["Can I pay by card in Berlin?", "cash"],
  ["Is the Berlin airport finally open?", "mobility-ber"],
  ["When is Oktoberfest in Munich?", "beer"],
  ["How do I get a Termin at the Bürgeramt in Berlin?", "termin"],
  ["Is the Weihnachtsmarkt in Dresden open?", "culture-weihnachtsmarkt"],
];
