// Alternative phrasings for existing topics: [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  // core
  ["gewerbeanmeldung", "business"],
  ["so i want to sell handmade candles online, do i need to register that somewhere", "business"],
  ["ummelden", "anmeldung"],
  ["meldebescheinigung verloren", "anmeldung"],
  ["new address registration germany", "anmeldung"],
  ["reisepass beantragen dauer", "passport"],
  ["my passport photo got rejected", "passport"],
  ["auto ummelden", "car"],
  ["kfz zulassung termin", "car"],
  ["steuererklaerung", "tax"],
  ["do i have to file taxes if i only earned a little", "tax"],
  ["ICE verspätet schon wieder", "train"],
  ["db app says my train is cancelled what now", "train"],
  ["ladenoeffnungszeiten sonntag", "sunday"],
  ["rubbish collection rules", "trash"],
  ["where does the garbage go", "trash"],
  ["gelber sack oder restmuell", "trash"],
  ["muelltrennung", "trash"],
  ["hundesteuer anmelden", "dog"],
  ["kita platz", "kita"],
  ["kindergarten spot for my daughter", "kita"],
  ["why can i only send documents by fax and not email", "digital"],
  ["standesamt hochzeit termin", "marriage"],
  ["do shops take apple pay", "cash"],
  ["looking for a flat in munich", "housing"],
  ["wohnungssuche berlin unmöglich", "housing"],
  ["buergeramt termin frei", "termin"],
  ["gez", "rundfunk"],
  ["beitragsservice brief bekommen", "rundfunk"],
  ["facharzt termin", "health"],
  ["krankmeldung arbeitgeber", "sicknote"],
  ["handyvertrag kuendigen", "tech-handyvertrag"],
  ["konto eroeffnen ohne schufa", "bank"],
  ["einbuergerung voraussetzungen", "citizenship"],
  ["urlaubstage pro jahr", "work"],
  ["what is a bridge day", "brueckentag"],
  ["wiesn tickets", "beer"],
  ["nachbar laerm nachts", "noise"],
  ["frau schulze", "schulze"],
  ["will it rain tomorrow", "weather"],
  ["stosslueften", "lueften"],
  ["is it rude not to tip in a restaurant", "restaurant"],
  ["fahrrad licht pflicht", "bike"],
  ["jaywalking fine", "redlight"],
  ["parkschein automat kaputt", "parking"],
  ["erzähl mir einen witz", "joke"],
  ["bist du ein bot", "identity"],
  ["i want to talk to a real person", "human"],
  ["einspruch gegen bescheid", "widerspruch"],
  ["are you open on friday", "hours"],
  ["broetchen", "food"],
  ["vorname nicht erlaubt", "babyname"],
  ["beglaubigte uebersetzung", "beglaubigung"],
  ["49 euro ticket", "deutschlandticket"],
  ["renteneintrittsalter", "pension"],
  ["paket nicht angekommen", "post"],
  ["faxgeraet", "fax"],
  // housing
  ["kehrwoche", "housing-kehrwoche"],
  ["nebenkostenabrechnung nachzahlung", "housing-nebenkosten"],
  ["my landlord sent me a huge utility bill", "housing-nebenkosten"],
  ["umzugskartons", "housing-umzug"],
  ["can i barbecue on my balcony", "housing-grill"],
  ["schornsteinfeger termin", "housing-schornsteinfeger"],
  ["stromanbieter wechseln", "housing-strom"],
  ["mietkaution zurück", "housing-kaution"],
  ["wg zimmer", "housing-wg"],
  ["sperrmuell anmelden", "housing-sperrmuell"],
  ["locked myself out", "housing-schluesseldienst"],
  // work
  ["minijob", "work-minijob"],
  ["steuerklasse wechseln nach heirat", "work-steuerklasse"],
  ["brutto netto rechner", "work-payslip"],
  ["arbeitsamt melden", "work-unemployment"],
  ["arbeitszeugnis", "work-zeugnis"],
  ["probezeit kuendigung", "work-contract"],
  ["my boss wants to fire me", "work-fired"],
  ["homeoffice pauschale", "work-homeoffice"],
  ["kuenstlersozialkasse", "work-ksk"],
  ["mindestlohn", "work-salary"],
  ["bewerbungsfoto", "work-application"],
  ["steuerberater finden", "work-steuerberater"],
  // mobility
  ["fuehrerschein umschreiben", "mobility-licence-conversion"],
  ["how much does a driving license cost here", "mobility-fahrschule"],
  ["tuev faellig", "mobility-tuev"],
  ["geblitzt", "mobility-speeding"],
  ["punkte in flensburg", "mobility-speeding"],
  ["flughafen ber", "mobility-ber"],
  ["my flight got cancelled compensation", "mobility-flights"],
  ["gdl streik", "mobility-strike"],
  ["flixbus", "mobility-fernbus"],
  ["e scooter rules", "mobility-escooter"],
  ["mein fahrrad wurde geklaut", "mobility-bike-theft"],
  ["bahncard 50", "mobility-bahncard"],
  ["schienenersatzverkehr", "mobility-sev"],
  ["winterreifen pflicht", "mobility-winter-tyres"],
  ["unfall gebaut was tun", "mobility-accident"],
  // family
  ["homeschooling erlaubt", "family-homeschool"],
  ["gymnasium empfehlung", "family-schoolsystem"],
  ["bafoeg antrag", "family-bafoeg"],
  ["hebamme finden", "family-hebamme"],
  ["elterngeld beantragen", "family-elterngeld"],
  ["impfpass verloren", "family-impfung"],
  ["apotheke notdienst", "family-apotheke"],
  ["privat versichert oder gesetzlich", "family-privat"],
  ["therapieplatz", "family-therapie"],
  ["pflegegrad beantragen", "family-pflege"],
  ["schultuete", "family-einschulung"],
  ["ausbildung suchen", "family-ausbildung"],
  // culture
  ["why are germans always on time", "culture-punctuality"],
  ["fasching", "culture-karneval"],
  ["gluehwein pfand", "culture-weihnachtsmarkt"],
  ["is the sauna really naked", "culture-sauna"],
  ["kleingarten", "culture-schrebergarten"],
  ["duzen oder siezen", "culture-duzen"],
  ["why are german words so long", "culture-language"],
  ["tatort", "culture-tatort"],
  ["silvester feuerwerk", "culture-silvester"],
  // government
  ["aufenthaltstitel verlaengern", "gov-residence-permit"],
  ["blaue karte eu", "gov-blue-card"],
  ["briefwahl", "gov-voting"],
  ["anzeige erstatten", "gov-police"],
  ["fundbuero", "gov-lost-property"],
  ["fuehrungszeugnis beantragen", "gov-fuehrungszeugnis"],
  ["balkonkraftwerk anmelden", "gov-energy"],
  ["steuer id vergessen", "gov-steuer-id"],
  ["wie werde ich beamter", "gov-beamter"],
  // smalltalk
  ["moin", "talk-greeting"],
  ["vielen dank", "talk-thanks"],
  ["tschuess", "talk-bye"],
  ["was kannst du", "talk-help"],
  ["notfall", "talk-urgent"],
  // long, rambling, two-topic and spelling variants
  ["ok so my landlord keeps texting me and my cat is sick and anyway how do i do the anmeldung", "anmeldung"],
  ["honestly i have been in germany for three weeks and still don't understand which bin the pizza box goes in", "trash"],
  ["my colleague told me i could just cross when the street is empty, is that true about red lights", "redlight"],
  ["we just had a baby, congrats to us, now how do we register the birth and pick a name the standesamt accepts", "life-birth-registration"],
  ["i moved from spain, i have a spanish licence, do i need to swap it for a german one", "mobility-licence-conversion"],
  ["my driver's license from the US, is it valid here or do i need to convert it", "mobility-licence-conversion"],
  ["the neighbours had a party until 3am on a tuesday, what are the quiet hours", "noise"],
  ["i'm freelancing as a designer, do i need to register a business or just tell the finanzamt", "business"],
  ["my flatmate moved out and now i need a new one, how does a wg casting work", "housing-wg"],
  ["the heating in my flat is broken and the hausverwaltung isn't answering", "housing-reparatur"],
  ["i got a letter from the beitragsservice although i live with my parents", "rundfunk"],
  ["train was 90 minutes late, can i get money back", "train"],
  ["my employer hasn't paid my christmas bonus, is weihnachtsgeld mandatory", "work-bonus"],
  ["i'm thinking of quitting my job but i'm still in the probationary period", "work-contract"],
  ["favourite german bread", "food"],
  ["organise a demonstration in berlin", "gov-demonstration"],
  ["center for lost property in munich", "gov-lost-property"],
  ["rubbish bins are full and collection is late", "trash"],
  ["cheque or bank transfer for the rent", "bank"],
  ["which tyres in winter", "mobility-winter-tyres"],
  ["wie lange dauert ein reisepass", "passport"],
  ["wie finde ich eine wohnung", "housing"],
  ["wann kommt mein zug", "train"],
  ["kann ich mit karte zahlen", "cash"],
  ["darf ich sonntags rasen maehen", "sunday"],
  ["wer ist frau schulze eigentlich", "schulze"],
  ["was kostet der rundfunkbeitrag", "rundfunk"],
  ["wie beantrage ich kindergeld", "kita"],
  ["wie viele urlaubstage habe ich", "work"],
];
