// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  // shop-returns
  ["How do I return something?", "shop-returns"],
  ["Can I exchange a sweater I bought last week?", "shop-returns"],
  ["what is the return policy in german shops", "shop-returns"],
  ["Was ist der Unterschied zwischen Garantie und Gewährleistung?", "shop-returns"],
  ["my phone is defective after 3 months", "shop-returns"],
  ["Kann ich das umtauschen?", "shop-returns"],
  ["how long is the warranty in germany", "shop-returns"],
  ["The toaster broke after two weeks, can I get my money back?", "shop-returns"],
  // shop-receipt
  ["Do I need to keep the Kassenbon?", "shop-receipt"],
  ["why do I always get a receipt", "shop-receipt"],
  ["Brauche ich eine Quittung?", "shop-receipt"],
  ["why does the bakery print a receipt for one roll", "shop-receipt"],
  ["kassenzettel aufbewahren", "shop-receipt"],
  // shop-checkout
  ["Why do I have to pack so fast at the checkout?", "shop-checkout"],
  ["why are aldi cashiers so fast", "shop-checkout"],
  ["Lidl checkout stress", "shop-checkout"],
  ["how does the self checkout work", "shop-checkout"],
  ["the cashier scans so fast I can't keep up", "shop-checkout"],
  ["Why does everyone run when a second till opens?", "shop-checkout"],
  // shop-bags
  ["Why do shopping bags cost money?", "shop-bags"],
  ["are plastic bags banned in germany", "shop-bags"],
  ["Wie viel kostet eine Tüte?", "shop-bags"],
  ["why does everyone have a jutebeutel", "shop-bags"],
  ["do I need to bring my own tote bag", "shop-bags"],
  // shop-ladenschluss
  ["What time do supermarkets close?", "shop-ladenschluss"],
  ["when do shops close on saturday", "shop-ladenschluss"],
  ["Are shops open late in Germany?", "shop-ladenschluss"],
  ["What is a Späti?", "shop-ladenschluss"],
  ["Wann ist Ladenschluss?", "shop-ladenschluss"],
  ["is anything open 24 hours", "shop-ladenschluss"],
  ["where can I buy beer at midnight, is the kiosk open?", "shop-ladenschluss"],
  ["how late are stores open until", "shop-ladenschluss"],
  // shop-flohmarkt
  ["How do I sell my old stuff?", "shop-flohmarkt"],
  ["how does kleinanzeigen work", "shop-flohmarkt"],
  ["Where is the nearest flea market?", "shop-flohmarkt"],
  ["why does everyone ask 'was letzte preis'", "shop-flohmarkt"],
  ["Flohmarkt am Wochenende", "shop-flohmarkt"],
  ["is it safe to buy second hand furniture", "shop-flohmarkt"],
  ["selling on ebay in germany", "shop-flohmarkt"],
  // shop-prospekt
  ["Why is my letterbox full of flyers?", "shop-prospekt"],
  ["Are there good deals in the weekly flyer?", "shop-prospekt"],
  ["I have a keine werbung sticker but still get junk mail", "shop-prospekt"],
  ["what is the angebot der woche", "shop-prospekt"],
  ["Prospekt lesen am Mittwoch", "shop-prospekt"],
  ["why was the special offer sold out at 8am", "shop-prospekt"],
  // shop-drogerie
  ["What is a Drogerie?", "shop-drogerie"],
  ["where do I buy shampoo and toothpaste", "shop-drogerie"],
  ["dm or rossmann?", "shop-drogerie"],
  ["Is a drugstore the same as a pharmacy?", "shop-drogerie"],
  ["where can I buy cosmetics", "shop-drogerie"],
  // shop-baumarkt
  ["What happens at the Baumarkt on Saturday?", "shop-baumarkt"],
  ["Where can I buy tools?", "shop-baumarkt"],
  ["is obi or hornbach better", "shop-baumarkt"],
  ["I need a hardware store", "shop-baumarkt"],
  ["Heimwerken am Samstag", "shop-baumarkt"],
  // shop-wochenmarkt
  ["When is the farmers market?", "shop-wochenmarkt"],
  ["Can I touch the vegetables at the Wochenmarkt?", "shop-wochenmarkt"],
  ["where can I buy fresh vegetables", "shop-wochenmarkt"],
  ["weekly market opening times", "shop-wochenmarkt"],
  // shop-haggling
  ["Can I haggle in German shops?", "shop-haggling"],
  ["is it rude to ask for a discount in a shop", "shop-haggling"],
  ["can I negotiate the price at a supermarket", "shop-haggling"],
  ["Feilschen in Deutschland?", "shop-haggling"],
  // shop-bio
  ["Is organic food worth it?", "shop-bio"],
  ["what does the bio siegel mean", "shop-bio"],
  ["where is a bioladen", "shop-bio"],
  ["are there vegan options in german supermarkets", "shop-bio"],
  ["What is Demeter?", "shop-bio"],
  // shop-sparfuchs
  ["What is the cheapest way to shop?", "shop-sparfuchs"],
  ["what is a Sparfuchs", "shop-sparfuchs"],
  ["Why are Germans so frugal?", "shop-sparfuchs"],
  ["geiz ist geil?", "shop-sparfuchs"],
  ["how can I save on groceries", "shop-sparfuchs"],
  // shop-tupperware
  ["I got invited to a Tupperware party", "shop-tupperware"],
  ["Why does everyone have a Thermomix?", "shop-tupperware"],
  ["what is a thermomix party", "shop-tupperware"],
  // shop-payback
  ["Are there discount codes or loyalty cards?", "shop-payback"],
  ["Haben Sie eine Payback Karte?", "shop-payback"],
  ["what is payback", "shop-payback"],
  ["is a voucher a good gift", "shop-payback"],
  ["do I need a kundenkarte", "shop-payback"],
  // shop-schlussverkauf
  ["Is Black Friday a thing in Germany?", "shop-schlussverkauf"],
  ["when is the summer sale", "shop-schlussverkauf"],
  ["Wann ist Schlussverkauf?", "shop-schlussverkauf"],
  ["why is this furniture store always having a clearance sale", "shop-schlussverkauf"],
  // shop-einkaufswagen
  ["Why do I need a coin for the shopping cart?", "shop-einkaufswagen"],
  ["How do I get a shopping trolley?", "shop-einkaufswagen"],
  ["Einkaufswagen ohne Chip", "shop-einkaufswagen"],
  ["i have no euro coin for the cart", "shop-einkaufswagen"],
  // shop-groceries
  ["Why is food so expensive?", "shop-groceries"],
  ["which supermarket is best", "shop-groceries"],
  ["Edeka or Rewe?", "shop-groceries"],
  ["grocery prices in germany", "shop-groceries"],
  ["where do I buy groceries", "shop-groceries"],
  ["what is a discounter", "shop-groceries"],
  // shop-online
  ["Can I return something I ordered online?", "shop-online"],
  ["how do I send it back to amazon", "shop-online"],
  ["online shopping in germany", "shop-online"],
  ["I need a return label for zalando", "shop-online"],
  ["Widerrufsrecht 14 Tage", "shop-online"],
  // existing topics that fit better
  ["Can I go shopping on Sunday?", "sunday"],
  ["can I pay by card at aldi", "cash"],
  ["Where do I return Pfand bottles?", "trash"],
];
