// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  ["hi", "talk-greeting"],
  ["Hello!", "talk-greeting"],
  ["hallo", "talk-greeting"],
  ["Moin moin", "talk-greeting"],
  ["Guten Tag", "talk-greeting"],
  ["Grüß Gott", "talk-greeting"],
  ["servus", "talk-greeting"],
  ["thanks!", "talk-thanks"],
  ["Thank you so much", "talk-thanks"],
  ["danke", "talk-thanks"],
  ["vielen Dank für die Hilfe", "talk-thanks"],
  ["you're the best", "talk-thanks"],
  ["bye", "talk-bye"],
  ["tschüss", "talk-bye"],
  ["Auf Wiedersehen", "talk-bye"],
  ["good night", "talk-bye"],
  ["what can you do?", "talk-help"],
  ["how does this work", "talk-help"],
  ["Hilfe", "talk-help"],
  ["what is this website", "talk-help"],
  ["how are you?", "talk-howareyou"],
  ["wie geht's?", "talk-howareyou"],
  ["are you there?", "talk-howareyou"],
  ["whats up", "talk-howareyou"],
  ["you are useless", "talk-insult"],
  ["this is stupid", "talk-insult"],
  ["du bist so dumm", "talk-insult"],
  ["worst website ever", "talk-insult"],
  ["I love you", "talk-love"],
  ["will you marry me?", "talk-love"],
  ["are you single?", "talk-love"],
  ["yes", "talk-yesno"],
  ["no", "talk-yesno"],
  ["ok", "talk-yesno"],
  ["nein", "talk-yesno"],
  ["maybe", "talk-yesno"],
  ["I don't understand", "talk-confused"],
  ["what?", "talk-confused"],
  ["wie bitte?", "talk-confused"],
  ["this makes no sense", "talk-confused"],
  ["Sprichst du Deutsch?", "talk-language"],
  ["can you answer in english please", "talk-language"],
  ["do you speak spanish", "talk-language"],
  ["test", "talk-gibberish"],
  ["asdf", "talk-gibberish"],
  ["haha", "talk-gibberish"],
  ["lol", "talk-gibberish"],
  ["is this real?", "talk-real"],
  ["Is this a real government website?", "talk-real"],
  ["is this satire", "talk-real"],
  ["who made this?", "talk-creator"],
  ["who built this site", "talk-creator"],
  ["is this open source?", "talk-creator"],
  ["tell me a fun fact", "talk-funfact"],
  ["I'm bored", "talk-funfact"],
  ["tell me something about Germany", "talk-funfact"],
  ["what time is it?", "talk-time"],
  ["what day is it today", "talk-time"],
  ["wie spät ist es", "talk-time"],
  ["this is an emergency", "talk-urgent"],
  ["it's urgent!!", "talk-urgent"],
  ["Notfall", "talk-urgent"],
  ["hurry up", "talk-slow"],
  ["why is this so slow", "talk-slow"],
  ["can you be faster", "talk-slow"],
  ["what is the meaning of life", "talk-meaning"],
  ["42", "talk-meaning"],
  ["what do you recommend?", "talk-advice"],
  ["what should I do", "talk-advice"],
  ["any tips for living in germany?", "talk-advice"],
  ["sorry", "talk-sorry"],
  ["my bad", "talk-sorry"],
  ["Verzeihung", "talk-sorry"],
  // A greeting in front of a real question: the real topic must win.
  ["hi, how do I register my car?", "car"],
  ["hello, why is my train late?", "train"],
  ["hey, which bin does a yoghurt pot go in?", "trash"],
  ["thanks, and how do I cancel my gym contract?", "kuendigung"],
  ["moin, do I have to pay the Rundfunkbeitrag?", "rundfunk"],
  ["ok but can I pay by card", "cash"],
];
