// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  // Handyvertrag
  ["How do I cancel my phone contract?", "tech-handyvertrag"],
  ["Handyvertrag kündigen", "tech-handyvertrag"],
  ["how long is a mobile contract in germany", "tech-handyvertrag"],
  ["My phone contract renewed automatically, can I get out?", "tech-handyvertrag"],
  ["Which Handytarif should I choose?", "tech-handyvertrag"],
  ["Wie lange läuft ein Mobilfunkvertrag?", "tech-handyvertrag"],
  // Prepaid SIM
  ["Do I need ID for a prepaid SIM card?", "tech-prepaid"],
  ["how do i get a sim card as a tourist", "tech-prepaid"],
  ["Prepaid Karte aktivieren", "tech-prepaid"],
  ["Can I get an eSIM in Germany?", "tech-prepaid"],
  ["Wo bekomme ich eine SIM-Karte?", "tech-prepaid"],
  // Router / WiFi
  ["How do I set up my WiFi router?", "tech-router"],
  ["what is my fritzbox password", "tech-router"],
  ["Why is there no free WiFi in Germany?", "tech-router"],
  ["Is public wifi safe?", "tech-router"],
  ["Was ist die Störerhaftung?", "tech-router"],
  ["Can I share my WLAN with my neighbour?", "tech-router"],
  ["wlan passwort vergessen", "tech-router"],
  // Provider / technician
  ["How do I switch my internet provider?", "tech-provider"],
  ["The Telekom technician never came", "tech-provider"],
  ["Anbieterwechsel Internet wie lange?", "tech-provider"],
  ["my internet connection is slower than promised", "tech-provider"],
  ["Which internet provider is best?", "tech-provider"],
  ["When will the technician come to install my DSL?", "tech-provider"],
  ["Is Vodafone or O2 better?", "tech-provider"],
  // Hotline
  ["Why is the hotline always busy?", "tech-hotline"],
  ["I've been on hold for an hour", "tech-hotline"],
  ["kundenservice nicht erreichbar", "tech-hotline"],
  ["How do I reach customer service?", "tech-hotline"],
  ["endlose Warteschleife", "tech-hotline"],
  // GEMA / YouTube
  ["Why are some YouTube videos blocked?", "tech-gema"],
  ["What is GEMA?", "tech-gema"],
  ["this video is not available in your country", "tech-gema"],
  ["Do I need a GEMA licence for my street party?", "tech-gema"],
  // Streaming
  ["Can I share my Netflix password?", "tech-streaming"],
  ["Is streaming legal in Germany?", "tech-streaming"],
  ["Why is everything dubbed on Netflix?", "tech-streaming"],
  ["What is the ARD Mediathek?", "tech-streaming"],
  ["Spotify Familie teilen erlaubt?", "tech-streaming"],
  // Filesharing
  ["Can I get in trouble for downloading movies?", "tech-filesharing"],
  ["I got an Abmahnung for downloading a film", "tech-filesharing"],
  ["is torrenting illegal in germany", "tech-filesharing"],
  ["Do I need a VPN in Germany?", "tech-filesharing"],
  ["Filesharing Abmahnung was tun?", "tech-filesharing"],
  // Games
  ["Is my child allowed to play video games?", "tech-games"],
  ["What does USK 16 mean?", "tech-games"],
  ["Why was the blood green in German video games?", "tech-games"],
  ["When is gamescom?", "tech-games"],
  ["Is gaming a sport in Germany?", "tech-games"],
  ["Ab wann darf mein Kind Computerspiele spielen?", "tech-games"],
  // Printer / scanning
  ["How do I print and sign a PDF?", "tech-printer"],
  ["my printer doesn't work", "tech-printer"],
  ["Can I scan my documents with my phone?", "tech-printer"],
  ["Where can I print something?", "tech-printer"],
  ["Dokument einscannen und schicken", "tech-printer"],
  ["Drucker druckt nicht", "tech-printer"],
  // Attachments / email
  ["Why is my email attachment too big?", "tech-attachment"],
  ["What was De-Mail?", "tech-attachment"],
  ["The file is too big to send", "tech-attachment"],
  ["Should I use GMX or web.de?", "tech-attachment"],
  ["Anhang zu groß", "tech-attachment"],
  // Cookies
  ["Why are there so many cookie banners?", "tech-cookies"],
  ["Do I have to accept all cookies?", "tech-cookies"],
  ["how do I reject cookies", "tech-cookies"],
  ["Why does your cookie banner keep coming back?", "tech-cookies"],
  // WhatsApp / social
  ["Why is the parents' WhatsApp group so annoying?", "tech-whatsapp"],
  ["Can the Behörde contact me on WhatsApp?", "tech-whatsapp"],
  ["Is LinkedIn or XING more popular in Germany?", "tech-whatsapp"],
  ["Elterngruppe verlassen", "tech-whatsapp"],
  ["Which messenger do Germans use?", "tech-whatsapp"],
  // Smart home
  ["Can I put a security camera on my house?", "tech-smarthome"],
  ["Is a dashcam legal in Germany?", "tech-smarthome"],
  ["Is Alexa always listening?", "tech-smarthome"],
  ["Darf ich eine Videotürklingel anbringen?", "tech-smarthome"],
  ["Can I install a video doorbell?", "tech-smarthome"],
  // AI at work
  ["Can I use ChatGPT at work?", "tech-ai-work"],
  ["Is AI allowed at work in Germany?", "tech-ai-work"],
  ["Darf ich KI am Arbeitsplatz nutzen?", "tech-ai-work"],
  ["Which AI tool can I use for my job?", "tech-ai-work"],
  // E-waste
  ["Where do I recycle my old phone?", "tech-ewaste"],
  ["How do I dispose of batteries?", "tech-ewaste"],
  ["Wohin mit Elektroschrott?", "tech-ewaste"],
  ["Can I throw my old laptop in the trash?", "tech-ewaste"],
  ["what do I do with a broken light bulb", "tech-ewaste"],
  // Phones in school
  ["Is there a Handyverbot in schools?", "tech-school-phones"],
  ["Are phones allowed in school in Germany?", "tech-school-phones"],
  ["How much screen time is okay for kids?", "tech-school-phones"],
  ["What happened with the DigitalPakt Schule?", "tech-school-phones"],
  // Banking / phishing
  ["What is a TAN?", "tech-banking"],
  ["I got a scam SMS about my parcel", "tech-banking"],
  ["Is online banking safe in Germany?", "tech-banking"],
  ["Someone asked for my TAN on the phone", "tech-banking"],
  ["phishing email from my bank", "tech-banking"],
  ["pushTAN funktioniert nicht", "tech-banking"],
  // Passwords / security
  ["How do I choose a safe password?", "tech-password"],
  ["I think I was hacked", "tech-password"],
  ["Should I use a password manager?", "tech-password"],
  ["What does the BSI recommend?", "tech-password"],
  ["How do I set up 2FA?", "tech-password"],
  ["Mein Account wurde gehackt", "tech-password"],
  // TV reception
  ["How do I get cable TV?", "tech-tv"],
  ["What happened to the Nebenkostenprivileg?", "tech-tv"],
  ["Do I need DVB-T2?", "tech-tv"],
  ["Can I put a satellite dish on my balcony?", "tech-tv"],
  ["Kabelfernsehen kündigen", "tech-tv"],
  // Existing topics that fit better
  ["Why is the internet so slow in Germany?", "digital"],
  ["Is there Glasfaser in my street?", "digital"],
];
