// [question as a user would type it, expected topic id]
export const questions: [string, string][] = [
  ["What is a Minijob?", "work-minijob"],
  ["how much can i earn with a minijob", "work-minijob"],
  ["Can I have a Minijob next to my main job?", "work-minijob"],
  ["Ich suche einen Nebenjob, was muss ich beachten?", "work-minijob"],
  ["Which tax class should I choose after marriage?", "work-steuerklasse"],
  ["Welche Steuerklasse habe ich?", "work-steuerklasse"],
  ["what's the difference between tax class 3 and 5", "work-steuerklasse"],
  ["Why is my netto so much lower than my brutto?", "work-payslip"],
  ["Can you explain my payslip?", "work-payslip"],
  ["what are all these deductions on my salary", "work-payslip"],
  ["Warum ist meine Lohnabrechnung so kompliziert?", "work-payslip"],
  ["How much social security do I pay?", "work-payslip"],
  ["I lost my job, what now?", "work-unemployment"],
  ["How do I apply for Arbeitslosengeld?", "work-unemployment"],
  ["What is Bürgergeld?", "work-unemployment"],
  ["When do I have to register with the Jobcenter?", "work-unemployment"],
  ["Wie melde ich mich arbeitslos?", "work-unemployment"],
  ["How do I get a good Arbeitszeugnis?", "work-zeugnis"],
  ["What does 'stets zu unserer vollsten Zufriedenheit' mean?", "work-zeugnis"],
  ["my employer wrote a weird reference letter", "work-zeugnis"],
  ["What happens during the Probezeit?", "work-contract"],
  ["How long is the probation period?", "work-contract"],
  ["Is my fixed-term contract legal?", "work-contract"],
  ["what is the notice period for my employment contract", "work-contract"],
  ["Can my employer fire me?", "work-fired"],
  ["I got fired without warning, is that allowed?", "work-fired"],
  ["What is an Abmahnung?", "work-fired"],
  ["Kündigungsschutz – wie funktioniert das?", "work-fired"],
  ["Can I work from home?", "work-homeoffice"],
  ["What are the rules for working from home?", "work-homeoffice"],
  ["Ist Homeoffice ein Recht?", "work-homeoffice"],
  ["Do I need to join the Künstlersozialkasse?", "work-ksk"],
  ["what is scheinselbstständigkeit", "work-ksk"],
  ["Do I have to pay into a private pension?", "work-altersvorsorge"],
  ["Is Riester worth it?", "work-altersvorsorge"],
  ["what is a Betriebsrente", "work-altersvorsorge"],
  ["How do I save money in Germany?", "work-savings"],
  ["Should I get a Bausparvertrag?", "work-savings"],
  ["Why do Germans love the Sparbuch?", "work-savings"],
  ["is investing in ETFs normal here", "work-savings"],
  ["How do I get a tax refund?", "work-taxrefund"],
  ["Can I claim the Pendlerpauschale?", "work-taxrefund"],
  ["what are Werbungskosten", "work-taxrefund"],
  ["Do I get a Christmas bonus?", "work-bonus"],
  ["Gibt es Weihnachtsgeld?", "work-bonus"],
  ["Is a 13th salary normal in Germany?", "work-bonus"],
  ["How do I ask for a raise?", "work-salary"],
  ["What is the minimum wage?", "work-salary"],
  ["Why don't Germans talk about their salary?", "work-salary"],
  ["How much do people earn in Germany?", "work-salary"],
  ["What does a Gewerkschaft actually do?", "work-strike"],
  ["What is a Betriebsrat?", "work-strike"],
  ["Should I join a union?", "work-strike"],
  ["How do I apply for a job in Germany?", "work-application"],
  ["Do I need a photo on my CV?", "work-application"],
  ["How do I write a German cover letter?", "work-application"],
  ["tips for a job interview", "work-application"],
  ["Do I need to charge VAT as a freelancer?", "work-vat"],
  ["What is the Kleinunternehmerregelung?", "work-vat"],
  ["What needs to be on an invoice?", "work-vat"],
  ["Why is everything so expensive?", "work-inflation"],
  ["Why is inflation so high?", "work-inflation"],
  ["Do I need a Steuerberater?", "work-steuerberater"],
  ["How do I find a tax advisor?", "work-steuerberater"],
  ["How many vacation days do I get?", "work"],
  ["Do I have to pay Kirchensteuer?", "tax"],
  ["What is a Tarifvertrag?", "work-strike"],
  ["Welche Abzüge habe ich vom Bruttogehalt?", "work-payslip"],
  ["What is a Werkstudent?", "work-minijob"],
];
